// backend-cleaning/src/guarantee/entities/guarantee-claim.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.

// For demonstration, this enum is defined here, but it should ideally come from prisma/schema.prisma
// and be imported from `@prisma/client` if using Prisma Client types.
export enum ClaimStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  SETTLED = 'SETTLED',
}

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model GuaranteeClaim` in `schema.prisma`.
export interface GuaranteeClaim {
  id: string;
  bookingId: string;
  booking?: any; // Prisma relation to Booking
  clientId: string;
  client?: any; // Prisma relation to Client
  providerId: string;
  provider?: any; // Prisma relation to Provider
  description: string;
  attachments?: string[]; // URLs of photos/videos
  estimatedValue?: number; // Stored as Decimal in DB, number in TS
  resolvedValue?: number; // Final value paid/reimbursed, stored as Decimal
  status: ClaimStatus;
  resolutionNotes?: string;
  resolvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}