// backend-cleaning/src/coupons/entities/coupon.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.

// IMPORTANT: In a Prisma project, these enums and the Coupon interface
// should ideally be imported directly from `@prisma/client` (e.g., `import { CouponType, CouponTarget, CouponStatus, Coupon as PrismaCoupon } from '@prisma/client';`)
// after defining them in your `schema.prisma` file.
// This file is provided as a conceptual representation.

export enum CouponType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
}

export enum CouponTarget {
  ALL = 'ALL',
  NEW_CLIENTS = 'NEW_CLIENTS',
  SPECIFIC_SERVICE = 'SPECIFIC_SERVICE',
  SPECIFIC_PROVIDER = 'SPECIFIC_PROVIDER',
  NEW_CUSTOMER = 'NEW_CUSTOMER', // Adicionado conforme discussão
  REFERRAL_REFERRED = 'REFERRAL_REFERRED', // Adicionado conforme discussão
  REFERRAL_REFERRER = 'REFERRAL_REFERRER', // Adicionado conforme discussão
  MISSION_REWARD = 'MISSION_REWARD', // Adicionado conforme discussão
  REPEAT_CUSTOMER = 'REPEAT_CUSTOMER', // Adicionado conforme discussão
}

export enum CouponStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  EXPIRED = 'EXPIRED',
  USED_UP = 'USED_UP', // When maxUses is reached
}

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model Coupon` in `schema.prisma`.
export interface Coupon {
  id: string;
  code: string;
  type: CouponType;
  value: number; // Stored as Decimal in DB, number in TS
  validFrom: Date;
  validUntil: Date;
  maxUses?: number;
  usesCount: number;
  target: CouponTarget;
  targetId?: string;
  status: CouponStatus;
  createdAt: Date;
  updatedAt: Date;
  firstBookingOnly?: boolean; // NOVO CAMPO
  issuedToUserId?: string; // NOVO CAMPO: Para quem o cupom foi emitido (se for pessoal)
  issuedBy?:
    | 'SYSTEM'
    | 'MISSION'
    | 'REFERRAL'
    | 'LOYALTY_REDEEM'
    | 'RETURN_COUPON'; // NOVO CAMPO: Origem do cupom
  maxDiscount?: number; // NOVO CAMPO: Cap de desconto
  description?: string; // Adicionado para consistência com `create-coupon.dto.ts`
}

// NOVO: Classe CouponEntity para ser exportada e usada em DTOs/Controllers
export class CouponEntity implements Coupon {
  id: string;
  code: string;
  type: CouponType;
  value: number;
  validFrom: Date;
  validUntil: Date;
  maxUses?: number;
  usesCount: number;
  target: CouponTarget;
  targetId?: string;
  status: CouponStatus;
  createdAt: Date;
  updatedAt: Date;
  firstBookingOnly?: boolean;
  issuedToUserId?: string;
  issuedBy?:
    | 'SYSTEM'
    | 'MISSION'
    | 'REFERRAL'
    | 'LOYALTY_REDEEM'
    | 'RETURN_COUPON';
  maxDiscount?: number;
  description?: string;

  constructor(partial: Partial<CouponEntity>) {
    Object.assign(this, partial);
  }
}
