// backend-cleaning/src/pricing/entities/pricing-rule.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model PricingRule` in `schema.prisma`.
export interface PricingRule {
  id: string;
  zoneId?: string; // ID of the geographical zone (if applicable)
  dayOfWeek?: number; // 0-6 (Sunday-Saturday), null for all days
  startTime?: string; // E.g., "09:00"
  endTime?: string; // E.g., "17:00"
  demandThreshold?: number; // E.g., minimum number of bookings to activate surge
  surgeFactor: number; // Multiplier (e.g., 1.2 for 20% increase), stored as Decimal
  isActive: boolean;
  createdAt: Date;
  updatedAt: Date;
}
