// backend-cleaning/src/safety/entities/panic-alert.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.

// For demonstration, this enum is defined here, but it should ideally come from prisma/schema.prisma
// and be imported from `@prisma/client` if using Prisma Client types.
export enum PanicType {
  MEDICAL = 'MEDICAL',
  THREAT = 'THREAT',
  ACCIDENT = 'ACCIDENT',
  OTHER = 'OTHER',
}

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model PanicAlert` in `schema.prisma`.
export interface PanicAlert {
  id: string;
  userId: string;
  user?: any; // Prisma relation to User
  latitude: number;
  longitude: number;
  message?: string;
  status: string; // "ACTIVE", "RESOLVED", "FALSE_ALARM"
  createdAt: Date;
}
