// backend-cleaning/src/subscriptions/entities/subscription.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.
// In a NestJS app using Prisma, the Prisma client types are often used directly.

// For demonstration, these enums are defined here, but they should ideally come from prisma/schema.prisma
// and be imported from `@prisma/client` if using Prisma Client types.
export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  CANCELED = 'CANCELED',
  ACTION_REQUIRED_ADDRESS = 'ACTION_REQUIRED_ADDRESS',
  COMPLETED = 'COMPLETED',
}

export enum SubscriptionFrequency {
  WEEKLY = 'WEEKLY',
  BI_WEEKLY = 'BI_WEEKLY',
  MONTHLY = 'MONTHLY',
}

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model Subscription` in `schema.prisma`.
export interface Subscription {
  id: string;
  clientId: string;
  client?: any; // Prisma relation
  providerId: string;
  provider?: any; // Prisma relation
  providerServiceId: string;
  providerService?: any; // Prisma relation
  frequency: SubscriptionFrequency;
  startDate: Date;
  endDate?: Date;
  status: SubscriptionStatus;
  totalPrice: number;
  nextGenerationDate: Date;
  generatedBookings?: any[]; // Array of Booking objects
  createdAt: Date;
  updatedAt: Date;
}

// If you need a specific entity for recurring bookings (e.g., for a queue job payload)
export interface RecurringBookingJobPayload {
  subscriptionId: string;
  // Any other data needed to generate the booking
}
