// backend-cleaning/src/safety/entities/incident.entity.ts
// This file typically represents the structure of your database entity,
// often derived from Prisma models or defined for DTOs.

// For demonstration, these enums are defined here, but they should ideally come from prisma/schema.prisma
// and be imported from `@prisma/client` if using Prisma Client types.
export enum IncidentType {
  DAMAGE = 'DAMAGE',
  MISCONDUCT = 'MISCONDUCT',
  THEFT = 'THEFT',
  NO_SHOW = 'NO_SHOW',
  OTHER = 'OTHER',
}

export enum IncidentStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  REJECTED = 'REJECTED',
}

// This interface would typically be generated by Prisma Client or manually defined
// to match the `model Incident` in `schema.prisma`.
export interface Incident {
  id: string;
  reporterId: string;
  reporter?: any; // Prisma relation to User
  bookingId?: string;
  booking?: any; // Prisma relation to Booking
  type: IncidentType;
  description: string;
  attachments?: string[]; // URLs of evidence
  status: IncidentStatus;
  resolution?: string; // Description of the resolution
  resolvedBy?: string; // ID of the admin who resolved it
  resolvedAt?: Date;
  createdAt: Date;
  updatedAt: Date;
}